#!/usr/bin/env bash

factorize() {
    num=$1
    factors=$(factor "$num" | cut -d':' -f2 | tr ' ' '*')

    if [ -z "$factors" ]; then
        echo "Unable to factorize $num"
    else
        echo "$num=$factors"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
fi

while IFS= read -r num; do
    factorize "$num" || echo "Unable to factorize $num"
done < "$1"
