#!/usr/bin/env bash

factorize() {
    num=$1
    factors=""

    for ((i = 2; i <= num / 2; i++)); do
        if ((num % i == 0)); then
            factors+="=$i*$(($num / $i))\n"
            break
        fi
    done

    if [ -z "$factors" ]; then
        echo "Unable to factorize $num"
    else
        echo -e "$num$factors"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
fi

while IFS= read -r num; do
    factorize "$num" || echo "Unable to factorize $num"
done < "$1"
