#!/usr/bin/env bash

check_factor() {
    if [ $# -ne 1 ]; then
        num=$1
        factors=$(factor "$num")
        primes=${factors##"$num: "}
        IFS=' ' read -ra primes_arr <<< "$primes"

        if [ "${#primes_arr[@]}" -eq 2 ]; then
            echo "$num=${primes_arr[0]}*${primes_arr[1]}"
        else
            echo "Unable to factorize $num"
        fi
    else
        echo "Unable to factorize $1"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r num; do
        check_factor "$num"
    done < "$1"
fi
